run-dev:
	@echo "Running backend..."
	@RUST_LOG=trace cargo run

run-release:
	@echo "Running release backend..."
	@cargo run --release

build-dev:
	@echo "Building backend without optimizations..."
	@cargo build

build-release:
	@echo "Building backend with release flag..."
	@cargo build --release
